# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espectadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='espectador',
            name='carne_dia1',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Frango Assado', 'Frango Assado'), ('Linguiça', 'Linguiça'), ('Carne Assada na Brasa', 'Carne Assada na Brasa'), ('Galinha', 'Galinha')], default='Nenhuma', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='espectador',
            name='carne_dia2',
            field=models.CharField(choices=[('Nenhuma', 'Nenhuma'), ('Frango Assado', 'Frango Assado'), ('Linguiça', 'Linguiça'), ('Carne Assada na Brasa', 'Carne Assada na Brasa'), ('Galinha', 'Galinha')], default='Nenhuma', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='espectador',
            name='presente_dia1',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espectador',
            name='presente_dia2',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espectador',
            name='quentinha_dia1',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=3),
        ),
        migrations.AlterField(
            model_name='espectador',
            name='quentinha_dia2',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], max_length=3),
        ),
    ]
